### ISSUE TITLE
How to store images automatically, in a loop

### ISSUE THREAD

**Issue by charleswidnall** [daattali/shinyscreenshot#18] opened 2022-05-12 02:57 UTC
Hi Dean,

I'm trying to use screenshot in a loop, but the first two screenshots that are saved show the same image, and the indexing (through a reactiveValues) shows some peculiar behavior.

I'm including a reprex running 3 cases, a simplified version of what I need to do, which is to generate and store the screenshots of some hundreds of images. I include the code for the 3 js files, which should be uncommented and saved in the /www/ directory.

In the reprex,

-- On the ui side, the images are displayed with uiOutput, and inserted into a div, 'myDiv'.
-- After the images are rendered (in the server) and displayed (in ui), screenshot stores them in "C:\Temp\images".

That's the general idea. Ah, everything is in Windows.

When one runs the file, the 3 images are shown in the div but, when they are saved, the two screenshots correspond to the same 1st js file, and the third screenshot corresponds to the 2nd js file. There is no screenshot of the 3rd js file. I guess there must be some issue with the indexing through the reactiveValues, because in the end the code still wants to get a 4th js file that doesn't exist.

I had rather similar behavior with a for loop, instead of the reactiveValues: the 1st and the 2nd are repeated stored images.

Any suggestion on how to use screenshot in the loop will be welcome.

Thank you very much, 

Charles

_(Part of the code comes from https://stackoverflow.com/questions/61853507/using-r-shiny-server-for-controlling-cyclic-execution-in-while-loop.)_

__# The code with the 3 js files_

_# This is a small sample of the final code that will generate 500 images and_ 
_# save the screenshots in C:/Temp/images__

library(shiny)
library(shinyjs)
library(htmltools)       # for includeScript
library(shinyscreenshot)

_# Make sure this directory _exists__
_# uncomment and run if there is no 'Screens' folder in your 'Documents'_
_#  if(!file.exists("C:/Temp/images")){_
_#    dir.create("C:/Temp/images")_
_#  }_

ui <- fluidPage(

>   useShinyjs(), 
>   tags$head(HTML("<script src='https://cdn.plot.ly/plotly-2.12.1.min.js'></script>")),
>   tags$head(HTML("<script src='https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.min.js'></script>")),
>   fluidRow(tags$div(id='myDiv'), uiOutput("plotnow1", width = "100%"))

)
server <- function(input, output, session) {
  

>   rv <- reactiveValues(loop = 1)
>     observeEvent(rv$loop, { # input$clicky, {
>       if((rv$loop >= 1) && (rv$loop <= 3)){
>            print(paste0("rv$loop = ",rv$loop))
>            output$plotnow1  <- renderUI({ includeScript(paste0("./www/plotly_",rv$loop,".js")) })
>            Sys.sleep(1)
>            screenshot(id         = "myDiv",
>                       filename   = paste0("plotly_",rv$loop,"_screenshot"),
>                       server_dir = "C:/Temp/images/",
>                       download   = FALSE)
>            shinyjs::delay(1000, rv$loop <- rv$loop + 1)
>       }
>     })

}
shinyApp(ui, server)

**# ----------------------------- 3 Files to be saved in /www/**
_# ------------------ plotly_1.js_
var trace1 = {
  x: [1, 2, 3, 4],
  y: [10, 15, 13, 17],
  type: 'scatter'
};

var trace2 = {
  x: [1, 2, 3, 4],
  y: [16, 5, 11, 9],
  type: 'scatter'
};

var data = [trace1, trace2];

Plotly.newPlot('myDiv', data);

_# ------------------ plotly_2.js_
var trace1 = {
  x: [1, 2, 3, 4],
  y: [10, 15, 13, 17],
  mode: 'markers'
};

var trace2 = {
  x: [2, 3, 4, 5],
  y: [16, 5, 11, 9],
  mode: 'lines'
};

var trace3 = {
  x: [1, 2, 3, 4],
  y: [12, 9, 15, 12],
  mode: 'lines+markers'
};

var data = [ trace1, trace2, trace3 ];

var layout = {
  title:'Line and Scatter Plot'
};

Plotly.newPlot('myDiv', data, layout);

_# ------------------ plotly_3.js_
var trace1 = {
  x: [1, 2, 3, 4, 5],
  y: [1, 6, 3, 6, 1],
  mode: 'markers',
  type: 'scatter',
  name: 'Team A',
  text: ['A-1', 'A-2', 'A-3', 'A-4', 'A-5'],
  marker: { size: 12 }
};

var trace2 = {
  x: [1.5, 2.5, 3.5, 4.5, 5.5],
  y: [4, 1, 7, 1, 4],
  mode: 'markers',
  type: 'scatter',
  name: 'Team B',
  text: ['B-a', 'B-b', 'B-c', 'B-d', 'B-e'],
  marker: { size: 12 }
};

var data = [ trace1, trace2 ];

var layout = {
  xaxis: {
    range: [ 0.75, 5.25 ]
  },
  yaxis: {
    range: [0, 8]
  },
  title:'Data Labels Hover'
};

Plotly.newPlot('myDiv', data, layout);

**Comment by daattali** [comment] 2022-05-12 03:06
There's quite a lot of code here, can you try to post a minimal code example (and also format it properly with the github markdown please :) )

**Comment by charleswidnall** [comment] 2022-05-12 11:31
Hi Dean,

I'm trying to use screenshot in a loop, but the first two screenshots that are saved show the same image, and the indexing (through 'reactiveValues') shows some peculiar behavior.

I'm including a reprex running 3 cases, a simplified version of what I need to do, which is to generate and store the screenshots of hundreds of images. I include the code for the 3 js files, which should be uncommented and saved in the /www/ directory. (The files are attached as .txt - they have to be renamed as .js.)

In the reprex,

-- On the ui side, the images are displayed with uiOutput, and inserted into a div, 'myDiv'.
-- After the images are rendered (in the server) and displayed (in ui), screenshot stores them in "C:\Temp\images".

That's the general idea. Ah, everything is in Windows.

When one runs the code below, the 3 images are shown in the div but, when they are saved, the two screenshots correspond to the same 1st js file, and the third screenshot corresponds to the 2nd js file. There is no screenshot of the 3rd js file. I guess there must be some issue with the indexing through the reactiveValues, because in the end the code still wants to get a 4th js file that doesn't exist.

I had rather similar behavior with a _for_ loop, instead of the reactiveValues: the 1st and the 2nd are repeated stored images.

Any suggestion on how to use screenshot in the loop will be welcome.

Thank you very much,

Charles

(Part of the code comes from https://stackoverflow.com/questions/61853507/using-r-shiny-server-for-controlling-cyclic-execution-in-while-loop.)

```
_# This is a small sample of the final code that will generate 500 images and save the screenshots in C:/Temp/images_

library(shiny)
library(shinyjs)
library(htmltools) # for includeScript
library(shinyscreenshot)

# Make sure the C:/Temp/images directory exists. If not, uncomment next line.
# if(!file.exists("C:/Temp/images")){ dir.create("C:/Temp/images") }

ui <- fluidPage(
   useShinyjs(),
   tags$head(HTML("<script src='https://cdn.plot.ly/plotly-2.12.1.min.js'></script>")),
   tags$head(HTML("<script src='https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.min.js'></script>")),
   fluidRow(tags$div(id='myDiv'), uiOutput("plotnow1", width = "100%"))
)

server <- function(input, output, session) {
  rv <- reactiveValues(loop = 1)

  observeEvent(rv$loop, {
     if((rv$loop >= 1) && (rv$loop <= 3)){ # do it for files 1 to 3
        print(paste0("rv$loop = ",rv$loop))

        # --- create the image
        output$plotnow1 <- renderUI({ 
            includeScript(paste0("./www/plotly_",rv$loop,".js")) 
        })
        Sys.sleep(1)

        # --- screenshot
        screenshot(id = "myDiv",
            filename = paste0("plotly_",rv$loop,"_screenshot"),
            server_dir = "C:/Temp/images/",
            download = FALSE
         )
        shinyjs::delay(1000, rv$loop <- rv$loop + 1)
      }
  })
}

shinyApp(ui, server)
```

**Comment by charleswidnall** [comment] 2022-05-12 11:32
These files have to be renamed *.js, and stored in the /www/ directory.

[plotly_2.txt](https://github.com/daattali/shinyscreenshot/files/8678611/plotly_2.txt)
[plotly_3.txt](https://github.com/daattali/shinyscreenshot/files/8678612/plotly_3.txt)
[plotly_1.txt](https://github.com/daattali/shinyscreenshot/files/8678613/plotly_1.txt)

**Comment by daattali** [comment] 2022-05-13 04:33
I'm sorry but there are too many moving parts in this code. It's a large piece of code with custom javascript files and external javascript liraries. When there are so many pieces, you cannot isolate the bug and pinpoint it blame one specific piece. If you believe there's an issue with {shinyscreenshot}, please try to come up with a small minimal example that uses as little code as possible and no other dependencies, that will prove the problem lies with this package and that will make it possible for me to start to troubleshoot.

**Comment by charleswidnall** [comment] 2022-05-16 12:31
Thanks, Dean, for your comments. In reality, for security, the javascript files come from https://plotly.com/javascript/line-and-scatter/. I don't think it's possible to create a much shorter reprex that reproduces all the basic features: iteration, loading and running external files, and screenshot, plus the inclusion of tags for libraries and the required ui/server code. Anyway, I should perhaps rephrase the question ... Is it possible to use screenshot in a loop where it can load and download images automatically (no clicking anywhere except, perhaps, for an initial one to kick off the process)? Or screenshot cannot be used in that fashion? Thanks again.

**Comment by daattali** [comment] 2022-05-16 20:17
Screenshots can be taken in a loop. Here's a small example

```
library(shiny)
library(shinyscreenshot)

ui <- fluidPage(
    actionButton("go", "go")
)

server <- function(input, output, session) {
  observeEvent(input$go, {
    for (i in seq(3)) {
      insertUI("body", "beforeEnd", paste0(i, runif(1)), immediate = TRUE)
      screenshot(filename = paste0("screenshot", i))
      Sys.sleep(2)
    }
  })
}

shinyApp(ui, server)
```

I'm closing this issue for now because I strongly believe that the main claim that screenshot can't work in a loop is incorrect.

If you still believe there is a bug , feel free to open a new issue, but please provide a **minimal isolated** example - one that highlights the problem is with shinyscreenshot

**Closed as completed by daattali** 2022-05-16 20:17 UTC

**Comment by charleswidnall** [comment] 2022-05-17 00:22
I don't think there is a bug or a problem with shinyscreenshot. Please note that the objective regarding the loop was about loading and storing images _automatically_, without clicking on the "Save" button opened by the File Explorer window. As it is now, one still has to click "Save" for each image that one wants to store. Thanks.

**Comment by daattali** [comment] 2022-05-17 05:01
You can save the images on the computer that's hosting the shiny app automaticaly - by using `screenshot(download = FALSE, server_dir = "path/to/save"`

But if the shiny app is hosted online and you want to download to the client/user computer, then that's not possible for shiny to have control over. The web browser decides how to handle downloads from a web page onto a client computer, for security reasons no web technology can have a say over that.
